name: PHPUnit

on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: PHPUnit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.2','8.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        run: composer install --no-progress

      - name: PHPUnit / PHP ${{ matrix.php-version }}
        run: ./vendor/bin/phpunit
